name: natural_language_shell
description: A terminal-like application for use with common language

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  record: ^4.4.4
  http:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/keys/
